<theme extends="webstandard" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd" >
	<resources>
		<styleSheet href="/style.css"/>
	</resources>
	
	<control>
		<name>ViewRoot</name>
		<property mode="concat">
			<name>pageTitle</name>
			<value>#{database.title}</value>
		</property>
	</control>
</theme>
